### ISSUE TITLE
Error: Unexpected end of JSON input at JSON.parse on Mac

### ISSUE THREAD

**Issue by Yiddishe-Kop** [Inventsable/CEP-Spy#1]
Hi,

I generated a fresh panel with Bombino on Mac, and I get this error:
![CleanShot 2020-06-10 at 5 00 00](https://user-images.githubusercontent.com/36875437/84277301-fdefe900-ab3b-11ea-96e2-89ef65633a75.png)
After digging around a while - I figured out the cause: in `cep-spy/index.js` all the filepaths are failing on Mac. 
I needed to fix 2 things:
1. Add `/` at beginning of each path.
2. Replace spaces in filenames with `\ ` (Mac system folder `Application Support` has a space).

Something like so:
```js
author: JSON.parse(
    window.cep.fs.readFile(
      `${decodeURI(window.__adobe_cep__.getSystemPath("extension")).replace(
        /file\:\/{1,}/,
        "/"
      ).replace(/\s/g, "\ ")}/package.json`
    ).data
  ).author,
```

I fixed it in the above file, but I assume we should only do it on a Mac..

Should I open a pull request, or you prefer to do it?

p.s. thanks for this awesome tool! 😎

**Comment by Inventsable** [comment]
Sorry for the delayed response, just started a new job and was very busy. Hopefully this is a decently straightforward fix:

```js
  author: JSON.parse(
    window.cep.fs.readFile(
      getRealString(
        `${decodeURI(window.__adobe_cep__.getSystemPath("extension")).replace(
          /file\:\/{1,}/,
          ""
        )}/package.json`
      )
    ).data
  ).author,
```

Where `getRealString` is:

```js
function getRealString(string) {
  return navigator.platform.indexOf("Mac") > -1
    ? `/${string}`.replace(/\s/g, "\\ ")
    : string;
}
```

If this works, it should solve for any bombino panel through an `npm install cep-spy@1.1.4` or `npm i cep-spy@latest` command, but:

1. I don't have a Mac to verify
2. I know of a few Mac users with bombino panels who never reported this, so it may not be the solution in the event it ends up breaking their current builds

Thanks for posting the issue! Would you mind verifying if this works before I update all the templates?

**Comment by Yiddishe-Kop** [comment]
Thanks for the fix!
---
I have tested, and it's working fine on Mac. On Windows though, it works in development, but is a blank white page in production...
I wonder what that could be...

**Edit**: The error was: `CSInterface.js: File not found`. For some reason it was looking in the wrong place. I put a copy in that place too, & it's working. 😀

**Comment by Inventsable** [comment]
Okay, cool! Thanks for the report. I'm going to transfer another user issue to this repo, then will try to merge these two together.

I have another Mac user claiming the space escaping on this is breaking for them. Possible that you two have different use cases or OS versions? I'll need to fix this for theirs as well, unless the space escaping in this is not required?

**Comment by Inventsable** [comment]
Here is what that user says:

> Thanx, for some reason, the window.cep.fs.readFile function does not like the escaping of the spaces when it is returned from the getRealString function. If you leave out the **.replace(/\s/g, "\ ")** part it works on the Mac (also with spaces in the path).

I'd like to move both of these to the same Issue since we're all talking about the same thing, and will need to find a solution that works for both of you. The original Issue was here:

https://github.com/battleaxedotco/bombino-brutalism-router/issues/1

Maybe it's worth creating a new function that we can test conditions on, whether each of you have different versions of Mac, or if space escaping wouldn't be necessary in anything not inside Application Support. I'll be looking into this in the next few hours and will try to refactor the original code again tonight

**Comment by Yiddishe-Kop** [comment]
Interesting. Looks like the double slash `\\ ` worked by me. I'll have a look into that.

But another thing that I don't understand - when I build & sign on Windows - the `archive` folder stays empty & I don't see a `.zxp` file (although the cli gives a success message).
When I take the `zxp` I signed on Mac, & install it on Windows - it has a white screen with this error:
```
Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Module.bf06 (file:///C:/Program%20Files%20(x86)/Common%20Files/Adobe/CEP/extensions/com.yiddishe-kop-scripts/dist/js/chunk-vendors.c92b6242.js:12:69386)
    at s (file:///C:/Program%20Files%20(x86)/Common%20Files/Adobe/CEP/extensions/com.yiddishe-kop-scripts/dist/js/app.004e4e60.js:1:564)
```

**Comment by Inventsable** [comment]
Okay. I may have broken something recently -- I'll verify with another production build. Just this week I've made probably 6 ZXPs (from Windows) which definitely worked on both Windows and Mac, so it may have to do with this latest PR.

**Comment by rbuikman** [comment]
fyi: I'm running on MacOS 10.15.5, node v12.18.0, npm 6.14.5

When I remove the **.replace(/\s/g, "\\ ")** in the getRealString function of the cep-spy/index.js (and same part in the lokney/node_modules/cep-spy it is working smoothly...

**Comment by Inventsable** [comment]
Hi guys, I've refactored everything as `cep-spy@1.2.0` and updated all related repos (brutalism, lokney, bombino templates) to be more in line with Mac instead of Windows. I believe this should work for every one:

```js
/**
 *
 * @param {String} str - The path to attempt resolution to
 * @param {Boolean} asJSON - If data should return as parsed JSON
 */
function resolveString(str, asJSON = false) {
  let result = path
    .resolve(
      str.replace(
        /file\:\/{1,}/,
        navigator.platform.indexOf("Mac") > -1 ? "/" : ""
      )
    )
    .replace(/\\{1}/gm, "/");
  return asJSON ? JSON.parse(result) : result;
}

/**
 *
 * @param {String} root - Base extension path
 * @param {String} file - Name of file to read
 * @param {String} key - When a parsed JSON, return as this key value
 * @param {Boolean} asJSON - If data should return as parsed JSON
 */

function tryReadingFile(root, file, key = "", asJSON = false) {
  root =
    root && root.length
      ? root
      : resolveString(window.__adobe_cep__.getSystemPath("extension"));
  let target = resolveString(`${root}/${file}`);
  if (fs.existsSync(target)) {
    let data = fs.readFileSync(target, "utf-8");
    return asJSON
      ? key || key.length
        ? JSON.parse(data)[key]
          ? JSON.parse(data)[key]
          : ""
        : JSON.parse(data)
      : data;
  } else {
    console.log("Target not found:", file, target);
    return null;
  }
}

```

Where in the above, we switch to `path.resolve()` instead of `decodeURI` (should solve the space discrepancy) and then switch to node's `fs` for reading files instead of CEP. This does mean that it's no longer standalone, but since the distribution was mainly through npm any way I doubt any one who isn't already using node is using CEP-Spy.

Let me know if this works, or if not what errors are produced. In a strange situation where I find myself with 3 Mac users all reporting different results and needs, but I think this was due to `decodeURI`

**Comment by rbuikman** [comment]
Sorry.... I'm now getting:

TypeError: fs.existsSync is not a function
    at tryReadingFile (webpack-internal:///./node_modules/cep-spy/index.js:36:10)
    at eval (webpack-internal:///./node_modules/cep-spy/index.js:270:16)
    at Module../node_modules/cep-spy/index.js (http://localhost:8080/js/chunk-vendors.js:47:1)

**Comment by Inventsable** [comment]
@rbuikman, is your vue.config.js file set to the same as below?

```js
module.exports = {
  publicPath: "./",
  configureWebpack: {
    target: "node-webkit",
    node: false,
  },
  lintOnSave: false,
};
```

Do you by chance have the `target` and `node` sections commented out and have yet to restart your dev server after modifying it?

**Comment by rbuikman** [comment]
Yes indeed, that was the problem (apologies). 
Great job, works like a charm on both Win and Mac!

**Comment by Yiddishe-Kop** [comment]
> Hi guys, I've refactored everything as cep-spy@1.2.0 and updated all related repos (brutalism, lokney, bombino templates) to be more in line with Mac instead of Windows. I believe this should work for every one:

I have updated my dependencies to the latest version & tested the build on Mac & Windows.
I can confirm that it's working perfectly on both platforms!

Thank you so much! 😃

**Comment by Inventsable** [comment]
Good to hear! Thanks for the patience. Going to go ahead and close this, let me know if you guys have any more issues with any of the tooling, especially the brutalism component library if either of you try it.

**Comment by rbuikman** [comment]
Sorry to bother you again... the plugin worked, but I just saw some "Target not found" messages in the CEP debug log...
To fix them, I needed to replace the %20 codes in the paths...

function resolveString(str, asJSON = false) {
  let result = path
    .resolve(
      str.replace(
        /file\:\/{1,}/,
        navigator.platform.indexOf("Mac") > -1 ? "/" : ""
      )
    )
    .replace(/\\{1}/gm, "/")**.replace(/\%20/g, " ");**
  return asJSON ? JSON.parse(result) : result;
}

**Comment by Inventsable** [comment]
@rbuikman Try now with `1.2.3`. Added a fallback that will check if the file exists without `%20` and use this instead

**Comment by rbuikman** [comment]
[0617/193906.248501:INFO:CONSOLE(96)] "Uncaught ReferenceError: root is not defined", source: webpack-internal:///./node_modules/cep-spy/index.js (96)

**Comment by Inventsable** [comment]
Sorry, had a typo. Just updated as `1.2.5`

**Comment by rbuikman** [comment]
sorry... 
webpack-internal:///./node_modules/cep-spy/index.js:100
    Object.keys(spy.paths).forEach((item) => {
           ^
TypeError: Cannot convert undefined or null to object

**Comment by rbuikman** [comment]
Please also check line 400, shouldn't that be the realSpy ?

**Comment by Inventsable** [comment]
Accidentally had `paths` instead of `path` for the key. On line 400 there shouldn't be a `realSpy` any more, just want to iterate through the original object so that you get the same path value for your use case in things like `spy.path.root` in the event you're loading scripts via `<Panel>` since it would likely not resolve correctly. Just fixed and republished

**Comment by rbuikman** [comment]
Cool! Works without warnings in the debug log now... Thanx a lot!

**Comment by Inventsable** [comment]
I'd verify that [your scripts are being loaded correctly by the Panel component](https://battleaxe.dev/brutalism-docs/#/Panel) if you happen to be using either brutalism or lokney (they share the same Panel/Menus code). If you have a `./src/host/[appName]/host.jsx` file and either have a `console.log` or `alert` statement, this should be evaluated on panel mount. Adding an `alert` then refreshing the panel should trigger this alert, and if so, the `Panel` component is correctly evaluating the file paths and we should be good

**Comment by Inventsable** [comment]
Tentatively going to close this again unless I hear back from any one. Thanks again for all the patience

**Comment by Inventsable** [comment]
Reopening this since I've noticed path resolution issue on Windows while handing off a ZXP. Trying to fix this right now

**Comment by Inventsable** [comment]
Believe this was fixed so closing again but let me know if anything was overlooked.
